"""Language definition patterns for codetre."""

_GET_NAME = lambda m: m['metaVariables']['single']['NAME']['text'].split('::')[-1].split('.')[-1]
_GET_OBJ_METHOD = lambda m: m['metaVariables']['single']['NAME']['text']

CALL_PATTERNS = {
    'python':      [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'javascript':  [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'typescript':  [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'tsx':         [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'cpp':         [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD),
                    ('$NAME($$$ARGS);', _GET_NAME),          ('$VAR = $NAME($$$ARGS)', _GET_NAME),
                    ('$TYPE $VAR = $NAME($$$ARGS)', _GET_NAME)],
    'c':           [('$NAME($$$ARGS)', _GET_NAME),          ('$NAME($$$ARGS);', _GET_NAME),
                    ('$VAR = $NAME($$$ARGS)', _GET_NAME),    ('$TYPE $VAR = $NAME($$$ARGS)', _GET_NAME)],
    'go':          [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'rust':        [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'ruby':        [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'java':        [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'kotlin':      [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'scala':       [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'csharp':      [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'php':         [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'swift':       [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'lua':         [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
    'bash':        [('$NAME($$$ARGS)', _GET_NAME)],
    'elixir':      [('$NAME($$$ARGS)', _GET_NAME)],
    'haskell':     [('$NAME($$$ARGS)', _GET_NAME)],
    'solidity':    [('$NAME($$$ARGS)', _GET_NAME),          ('$OBJ.$NAME($$$ARGS)', _GET_OBJ_METHOD)],
}

DEF_PATTERNS = {
    'python':      [('class $NAME', 'class'),                    ('def $NAME', 'func')],
    'javascript':  [('class $NAME', 'class'),                    ('function $NAME($$$ARGS)', 'func')],
    'typescript':  [('class $NAME', 'class'),                    ('interface $NAME { $$$BODY }', 'interface'),
                    ('function $NAME($$$ARGS)', 'func')],
    'tsx':         [('class $NAME', 'class'),                    ('interface $NAME { $$$BODY }', 'interface'),
                    ('function $NAME($$$ARGS)', 'func')],
    'cpp':         [('class $NAME', 'class'),                    ('$TYPE $NAME($$$PARAMS) { $$$BODY }', 'func')],
    'c':           [('$TYPE $NAME($$$PARAMS) { $$$BODY }', 'func')],
    'go':          [('type $NAME struct { $$$BODY }', 'struct'), ('type $NAME interface { $$$BODY }', 'interface'),
                    ('func $NAME($$$PARAMS)', 'func')],
    'rust':        [('struct $NAME { $$$BODY }', 'struct'),      ('trait $NAME { $$$BODY }', 'interface'),
                    ('impl $$$_ for $NAME { $$$BODY }', 'impl'), ('fn $NAME', 'func')],
    'ruby':        [('class $NAME', 'class'),                    ('def $NAME', 'func')],
    'java':        [('class $NAME { $$$BODY }', 'class'),        ('public class $NAME { $$$BODY }', 'class'),
                    ('interface $NAME { $$$BODY }', 'interface'),
                    ('$TYPE $NAME($$$PARAMS) { $$$BODY }', 'func'),
                    ('public $TYPE $NAME($$$PARAMS) { $$$BODY }', 'func'),
                    ('$NAME($$$PARAMS) { $$$BODY }', 'func')],
    'kotlin':      [('class $NAME', 'class'),                    ('interface $NAME { $$$BODY }', 'interface'),
                    ('fun $NAME($$$PARAMS)', 'func')],
    'scala':       [('class $NAME', 'class'),                    ('trait $NAME { $$$BODY }', 'interface'),
                    ('def $NAME($$$PARAMS)', 'func')],
    'csharp':      [('class $NAME', 'class'),                    ('interface $NAME { $$$BODY }', 'interface'),
                    ('$TYPE $NAME($$$PARAMS) { $$$BODY }', 'func')],
    'php':         [('class $NAME', 'class'),                    ('interface $NAME { $$$BODY }', 'interface'),
                    ('function $NAME($$$PARAMS)', 'func')],
    'swift':       [('class $NAME', 'class'),                    ('protocol $NAME { $$$BODY }', 'interface'),
                    ('func $NAME($$$PARAMS)', 'func')],
    'lua':         [('function $NAME($$$PARAMS)', 'func')],
    'bash':        [('function $NAME()', 'func')],
    'elixir':      [('defmodule $NAME', 'class'),                ('def $NAME($$$PARAMS)', 'func'),
                    ('defp $NAME($$$PARAMS)', 'func')],
    'haskell':     [('$NAME :: $$$TYPE', 'func')],
    'solidity':    [('contract $NAME { $$$BODY }', 'class'),     ('function $NAME($$$PARAMS)', 'func')],
}

LANG_MAP = {
    '.py': 'python', '.js': 'javascript', '.ts': 'typescript', '.tsx': 'tsx',
    '.cpp': 'cpp', '.cc': 'cpp', '.cxx': 'cpp', '.hpp': 'cpp', '.c': 'c', '.h': 'c',
    '.go': 'go',
    '.rs': 'rust', '.rb': 'ruby', '.java': 'java', '.kt': 'kotlin', '.scala': 'scala',
    '.cs': 'csharp', '.php': 'php', '.swift': 'swift',
    '.lua': 'lua', '.sh': 'bash', '.bash': 'bash', '.ex': 'elixir', '.exs': 'elixir',
    '.hs': 'haskell', '.sol': 'solidity',
}
